name: Deploy to Development

on:
  push:
    branches: [ develop, feature/* ]
  pull_request:
    branches: [ develop ]

env:
  AWS_REGION: us-east-1
  ENVIRONMENT: dev

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest
          
      - name: Lint Python code
        run: flake8 glue_jobs/ --max-line-length=120
        
      - name: Test Glue jobs
        run: pytest tests/

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Terraform Init
        working-directory: terraform/environments/dev
        run: terraform init
        
      - name: Terraform Plan
        working-directory: terraform/environments/dev
        run: terraform plan -var-file="../../../config/dev.tfvars"

  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/develop'
    environment: dev
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Terraform Init
        working-directory: terraform/environments/dev
        run: terraform init
        
      - name: Terraform Apply
        working-directory: terraform/environments/dev
        run: terraform apply -auto-approve -var-file="../../../config/dev.tfvars"
        
      - name: Deploy Glue Jobs
        run: |
          python scripts/deploy_glue_jobs.py --environment dev
          
      - name: Run Database Migrations
        run: |
          python scripts/run_migrations.py --environment dev
          
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Run integration tests
        run: |
          python -m pytest tests/integration/ -v